### ISSUE TITLE
Agent crashes during build

### ISSUE THREAD

**Issue by farshidtz** [cpswarm/deployment-tool#11]
Order:
```json
source:
  zip: UEsDBAoAAAAAAOp8WU4AAAAAAAAAAAAAAAAIAAAAcGFja2FnZS9QSwMECgAAAAAA6nxZTsMMtIOLAAAAiwAAABkAAABwYWNrYWdlL2NvdW50X3RvX3RocmVlLmdvcGFja2FnZSBtYWluCgppbXBvcnQgKAoJImZtdCIKCSJ0aW1lIgopCgpmdW5jIG1haW4oKSB7Cglmb3IgaSA6PSAxOyBpIDw9IDM7IGkrKyB7CgkJZm10LlByaW50bG4oImhlbGxvIiwgaSkKCQl0aW1lLlNsZWVwKHRpbWUuU2Vjb25kKQoJfQp9ClBLAQIUAAoAAAAAAOp8WU4AAAAAAAAAAAAAAAAIAAAAAAAAAAAAEAAAAAAAAABwYWNrYWdlL1BLAQIUAAoAAAAAAOp8WU7DDLSDiwAAAIsAAAAZAAAAAAAAAAAAAAAAACYAAABwYWNrYWdlL2NvdW50X3RvX3RocmVlLmdvUEsFBgAAAAACAAIAfQAAAOgAAAAAAA==

build:
  commands:
    - go build package/count_to_three.go
  artifacts:
    - count_to_three
  host: builder

deploy:
  install:
    commands:
      - chmod +x count_to_three

  run:
    commands:
      - ./count_to_three

  target:
    ids:
      - builder


debug: true
```

Logs:
```
2019/03/04 17:16:21 zeromq: Unsubscribed from cb52776b-4810-49a3-a053-8989cc7299d8:
2019/03/04 17:16:21 installer: Deploying 277 bytes of artifacts.
2019/03/04 17:16:21 installer: Installing task: cb52776b-4810-49a3-a053-8989cc7299d8
2019/03/04 17:16:21 installer: Install ended.
2019/03/04 17:16:21 installer: Removing files for task: cb52776b-4810-49a3-a053-8989cc7299d8
2019/03/04 17:16:21 installer: Removing: /home/tasks/c00c9dd8-956c-4b0b-8375-468082bb19c2
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe1 pc=0x7ff03c550d0a]

runtime stack:
runtime.throw(0x7ef9f7, 0x2a)
	/usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:374 +0x2f2

goroutine 20 [syscall]:
runtime.cgocall(0x5cf7e0, 0xc000165378, 0x29)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5e fp=0xc000165340 sp=0xc000165308 pc=0x403efe
os/user._Cfunc_mygetpwuid_r(0x0, 0xc0001b03f0, 0x7ff024000fd0, 0x400, 0xc0000ec070, 0xc000000000)
	_cgo_gotypes.go:181 +0x4d fp=0xc000165378 sp=0xc000165340 pc=0x52db8d
os/user.lookupUnixUid.func1.1(0x0, 0xc0001b03f0, 0x7ff024000fd0, 0x400, 0xc0000ec070, 0xc000165410)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:100 +0x135 fp=0xc0001653b8 sp=0xc000165378 pc=0x52ee85
os/user.lookupUnixUid.func1(0x7b2820)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:100 +0x50 fp=0xc0001653f8 sp=0xc0001653b8 pc=0x52ef20
os/user.retryWithBuffer(0xc0001463a0, 0xc0001654d0, 0xc0001463a0, 0x9)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:253 +0x3e fp=0xc000165450 sp=0xc0001653f8 pc=0x52ebce
os/user.lookupUnixUid(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:96 +0x130 fp=0xc000165508 sp=0xc000165450 pc=0x52e090
os/user.current(0xc000165570, 0x10, 0xc000165568)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:49 +0x27 fp=0xc000165538 sp=0xc000165508 pc=0x52de77
os/user.Current.func1()
	/usr/local/go/src/os/user/lookup.go:11 +0x22 fp=0xc000165560 sp=0xc000165538 pc=0x52ece2
sync.(*Once).Do(0xc2f520, 0x7f22a0)
	/usr/local/go/src/sync/once.go:44 +0xb3 fp=0xc000165590 sp=0xc000165560 pc=0x45eea3
os/user.Current(0x0, 0x0, 0xc000165600)
	/usr/local/go/src/os/user/lookup.go:11 +0x3d fp=0xc0001655c0 sp=0xc000165590 pc=0x52d5bd
os/user.LookupId(0x7edd65, 0x1, 0x1, 0x0, 0x0)
	/usr/local/go/src/os/user/lookup.go:38 +0x26 fp=0xc000165610 sp=0xc0001655c0 pc=0x52d696
archive/tar.statUnix(0x829aa0, 0xc0001b2ea0, 0xc0001da2a0, 0xc2f7a0, 0x0)
	/usr/local/go/src/archive/tar/stat_unix.go:39 +0x48a fp=0xc000165680 sp=0xc000165610 pc=0x537f2a
archive/tar.FileInfoHeader(0x829aa0, 0xc0001b2ea0, 0xc0001bc3c0, 0x43, 0x433753, 0x40c98f, 0x10000c000165868)
	/usr/local/go/src/archive/tar/common.go:702 +0x454 fp=0xc000165800 sp=0xc000165680 pc=0x531e04
code.linksmart.eu/dt/deployment-tool/vendor/github.com/mholt/archiver.tarFile.func1(0xc0001bc3c0, 0x43, 0x829aa0, 0xc0001b2ea0, 0x0, 0x0, 0x0, 0x0)
	/home/src/code.linksmart.eu/dt/deployment-tool/vendor/github.com/mholt/archiver/tar.go:143 +0x1e7 fp=0xc0001659c0 sp=0xc000165800 pc=0x591d17
path/filepath.walk(0xc0001bc3c0, 0x43, 0x829aa0, 0xc0001b2ea0, 0xc00014e180, 0x0, 0x40)
	/usr/local/go/src/path/filepath/path.go:358 +0x41c fp=0xc000165a98 sp=0xc0001659c0 pc=0x4df8cc
path/filepath.Walk(0xc0001bc3c0, 0x43, 0xc00014e180, 0xc0001b2dd0, 0x0)
	/usr/local/go/src/path/filepath/path.go:404 +0x105 fp=0xc000165af8 sp=0xc000165a98 pc=0x4dfa05
code.linksmart.eu/dt/deployment-tool/vendor/github.com/mholt/archiver.tarFile(0xc00017ca80, 0xc0001bc3c0, 0x43, 0x0, 0x0, 0xc0000ea210, 0xc000165bf8)
	/home/src/code.linksmart.eu/dt/deployment-tool/vendor/github.com/mholt/archiver/tar.go:138 +0x21a fp=0xc000165b90 sp=0xc000165af8 pc=0x58c67a
code.linksmart.eu/dt/deployment-tool/vendor/github.com/mholt/archiver.tarball(0xc000146370, 0x1, 0x1, 0xc00017ca80, 0x0, 0x0, 0xc0000ea1c0, 0xc000165c58)
	/home/src/code.linksmart.eu/dt/deployment-tool/vendor/github.com/mholt/archiver/tar.go:117 +0x83 fp=0xc000165be8 sp=0xc000165b90 pc=0x58c403
code.linksmart.eu/dt/deployment-tool/vendor/github.com/mholt/archiver.writeTar(0xc000146370, 0x1, 0x1, 0x827660, 0xc0001e40b0, 0x0, 0x0, 0x0, 0x0)
	/home/src/code.linksmart.eu/dt/deployment-tool/vendor/github.com/mholt/archiver/tar.go:110 +0x132 fp=0xc000165c48 sp=0xc000165be8 pc=0x58c2e2
code.linksmart.eu/dt/deployment-tool/vendor/github.com/mholt/archiver.writeTarGz(0xc000146370, 0x1, 0x1, 0x827320, 0xc0001b42a0, 0x0, 0x0, 0x0, 0x0)
	/home/src/code.linksmart.eu/dt/deployment-tool/vendor/github.com/mholt/archiver/targz.go:74 +0xbf fp=0xc000165ca8 sp=0xc000165c48 pc=0x58e2df
code.linksmart.eu/dt/deployment-tool/vendor/github.com/mholt/archiver.tarGzFormat.Write(0x827320, 0xc0001b42a0, 0xc000146370, 0x1, 0x1, 0x43, 0xc0001bc3c0)
	/home/src/code.linksmart.eu/dt/deployment-tool/vendor/github.com/mholt/archiver/targz.go:54 +0x5b fp=0xc000165d00 sp=0xc000165ca8 pc=0x58dfab
code.linksmart.eu/dt/deployment-tool/manager/model.CompressFiles(0xc000146370, 0x1, 0x1, 0x2, 0x2, 0xc0001bc3c0, 0x43, 0x24)
	/home/src/code.linksmart.eu/dt/deployment-tool/manager/model/compress.go:16 +0x77 fp=0xc000165d50 sp=0xc000165d00 pc=0x594fa7
main.(*agent).build(0xc0000e4000, 0xc0001b0090, 0xc00019a030, 0x24, 0xc00019a001)
	/home/src/code.linksmart.eu/dt/deployment-tool/agent/agent.go:235 +0x3e4 fp=0xc000165f08 sp=0xc000165d50 pc=0x5c4b14
main.(*agent).handleTask(0xc0000e4000, 0xc0001ac000, 0x228, 0x240)
	/home/src/code.linksmart.eu/dt/deployment-tool/agent/agent.go:204 +0x4e6 fp=0xc000165fc0 sp=0xc000165f08 pc=0x5c46b6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000165fc8 sp=0xc000165fc0 pc=0x456f01
created by main.(*agent).startWorker
	/home/src/code.linksmart.eu/dt/deployment-tool/agent/agent.go:79 +0x378

goroutine 1 [chan receive]:
main.main()
	/home/src/code.linksmart.eu/dt/deployment-tool/agent/main.go:61 +0x328

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 6 [select]:
main.(*logger).startTicker(0xc0000a22a0)
	/home/src/code.linksmart.eu/dt/deployment-tool/agent/logger.go:80 +0x19f
created by main.NewLogger
	/home/src/code.linksmart.eu/dt/deployment-tool/agent/logger.go:46 +0x15a

goroutine 7 [chan receive]:
main.(*agent).startWorker(0xc0000e4000)
	/home/src/code.linksmart.eu/dt/deployment-tool/agent/agent.go:63 +0x109
created by main.startAgent
	/home/src/code.linksmart.eu/dt/deployment-tool/agent/agent.go:54 +0x240

goroutine 8 [syscall]:
code.linksmart.eu/dt/deployment-tool/vendor/github.com/pebbe/zmq4._C2func_zmq_msg_recv(0xc00012a100, 0x11a18c0, 0x0, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:430 +0x55
code.linksmart.eu/dt/deployment-tool/vendor/github.com/pebbe/zmq4.(*Socket).RecvEvent.func1(0xc00012a100, 0x11a18c0, 0xc000000000, 0x0, 0xc00007e180, 0xc0000fef78)
	/home/src/code.linksmart.eu/dt/deployment-tool/vendor/github.com/pebbe/zmq4/zmq4.go:1110 +0x68
code.linksmart.eu/dt/deployment-tool/vendor/github.com/pebbe/zmq4.(*Socket).RecvEvent(0xc00008ac60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/src/code.linksmart.eu/dt/deployment-tool/vendor/github.com/pebbe/zmq4/zmq4.go:1110 +0x135
main.(*zmqClient).setupMonitor.func1()
	/home/src/code.linksmart.eu/dt/deployment-tool/agent/zeromq_client.go:167 +0x58
created by main.startZMQClient
	/home/src/code.linksmart.eu/dt/deployment-tool/agent/zeromq_client.go:83 +0x8df

goroutine 9 [syscall]:
code.linksmart.eu/dt/deployment-tool/vendor/github.com/pebbe/zmq4._C2func_zmq_msg_recv(0xc00012a2c0, 0x118c440, 0x0, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:430 +0x55
code.linksmart.eu/dt/deployment-tool/vendor/github.com/pebbe/zmq4.(*Socket).RecvBytes.func1(0xc00012a2c0, 0x118c440, 0xc000000000, 0x0, 0xc000041ea0, 0x40641f)
	/home/src/code.linksmart.eu/dt/deployment-tool/vendor/github.com/pebbe/zmq4/zmq4.go:964 +0x68
code.linksmart.eu/dt/deployment-tool/vendor/github.com/pebbe/zmq4.(*Socket).RecvBytes(0xc00008ac00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/src/code.linksmart.eu/dt/deployment-tool/vendor/github.com/pebbe/zmq4/zmq4.go:964 +0x196
code.linksmart.eu/dt/deployment-tool/vendor/github.com/pebbe/zmq4.(*Socket).Recv(0xc00008ac00, 0x0, 0x228, 0xc0001ac000, 0x228, 0x240)
	/home/src/code.linksmart.eu/dt/deployment-tool/vendor/github.com/pebbe/zmq4/zmq4.go:945 +0x39
main.(*zmqClient).startListener(0xc00008abd0)
	/home/src/code.linksmart.eu/dt/deployment-tool/agent/zeromq_client.go:94 +0x4c
created by main.startZMQClient
	/home/src/code.linksmart.eu/dt/deployment-tool/agent/zeromq_client.go:85 +0x904

goroutine 10 [chan receive]:
main.(*zmqClient).startResponder(0xc00008abd0)
	/home/src/code.linksmart.eu/dt/deployment-tool/agent/zeromq_client.go:114 +0x7f
created by main.startZMQClient
	/home/src/code.linksmart.eu/dt/deployment-tool/agent/zeromq_client.go:86 +0x929

goroutine 11 [chan receive]:
main.(*zmqClient).startOperator(0xc00008abd0)
	/home/src/code.linksmart.eu/dt/deployment-tool/agent/zeromq_client.go:126 +0x7f
created by main.startZMQClient
	/home/src/code.linksmart.eu/dt/deployment-tool/agent/zeromq_client.go:87 +0x94e

goroutine 19 [select]:
main.(*agent).connected(0xc0000e4000)
	/home/src/code.linksmart.eu/dt/deployment-tool/agent/agent.go:109 +0x1b4
created by main.(*agent).startWorker
	/home/src/code.linksmart.eu/dt/deployment-tool/agent/agent.go:67 +0x3cb
```

**Comment by farshidtz** [comment]
The error is caused only in Linux (tested amd64) when calling [tar.FileInfoHeader](https://github.com/mholt/archiver/blob/v2.1.0/tar.go#L143). 
Changed to zip archive for now.
